### PR TITLE
Keep text before changelog sections

### LINKED ISSUE #233: Ignore things before `#Changelog`
allow to have text in the cangelog before the #Changelog heading

e.g. allow to control linters: https://codeberg.org/woodpecker-plugins/editorconfig-checker/commit/f0a6121d54a3e8a3b3d2fad94c15e2570edcd45d

### PR DESCRIPTION
**Pull request by 6543**
close #233

based on #245

### CODE REVIEW

**Comment by anbraten** [comment]
Could we adjust this so we can keep custom text in changelog sections as well. So we could custom text like special migrations notes / highlights.

I was thinking of either creating a hook to intercept the generation or by using something like a comment `<!--- keep start -->` and `<!-- keep end -->`

**Comment by 6543** [comment]
:point_up: this looks like a new feature request: `Add syntax for manual content inside changelog` this pull here trys to just preserver anything before the changelog

**Comment by 6543** [comment]
@anbraten  Do you insist on addressing the change with your suggestion ?

**Comment by anbraten** [comment]
@6543 https://github.com/6543-forks/plugin-ready-release-go/pull/1

**Review by anbraten — APPROVED** [review]

**Pull request merged**
