### PR TITLE
Add `customReleaseBody` var and allow configuring `includeContributors`

### LINKED ISSUE #23: Support configuring release body
Currently hardcoded to `### ❤️ Thanks to all contributors! ❤️`

### PR DESCRIPTION
**Pull request by pat-s**
Same as #24 (delete the fork by mistake)

---

fix #23

- Add support for providing a custom release body via `customReleaseBody`
- Add support for configuring `includeContributors`
- Conditions the use of `customReleaseBody` on `includeContributors: true/false`

Disclaimer: I don't really know what should go into `config.user` and what into `config.ci` - let me know if things should be structured differently.

### CODE REVIEW

**Comment by anbraten** [comment]
This should already be doable by using `getReleaseDescription: (ctx: HookContext) => PromiseOrValue<string>;`

**Comment by anbraten** [comment]
`config.ci` is coming from env vars like `PLUGIN_...` or by `CI_...` metadata like the repo name. `config.user` contains all the options from the `.release-config.ts` file.

**Comment by pat-s** [comment]
> This should already be doable by using getReleaseDescription: (ctx: HookContext) => PromiseOrValue<string>;

I wasn't able to and hence still think this PR is required. I actually use a forked image right now in some projects with the changes of this PR.

Happy to move back to upstream if there's already a way to achieve what I was after. Maybe you can show how this can be done with HEAD as of now?

**Comment by pat-s** [comment]
@anbraten How to proceed here? Happy to close if the options described in the OP can already be done. But I couldn't manage so. Should I rebase to continue here or do you prefer to continue in a different way?

**Comment by anbraten** [comment]
@pat-s Why was `getReleaseDescription` not working for you 🤔

**Comment by pat-s** [comment]
I guess simply because I didn't know how to use it in the config file. I remember having tried it, it failed with an obscure syntax error and I gave up.

Can you share an example how to use it?
Or how to replicate the configuration in https://github.com/pat-s/otf-agent-helm which is based on a fork right now?

**Pull request closed without merging**
